version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pension-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pension_management_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Htht1234
      - SERVER_PORT=8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - pension-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pension-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pension-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: pension-mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Htht1234
      - MYSQL_DATABASE=pension_management_system
      - MYSQL_TCP_PORT=3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pension-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 10s

volumes:
  mysql_data:
    driver: local

networks:
  pension-network:
    driver: bridge