version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pension-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Htht1234
      MYSQL_DATABASE: pension_management_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: pension-backend
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pension_management_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Htht1234
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2

volumes:
  mysql_data:
