version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pension-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pension_management_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Htht1234
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - pension-net
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pension-frontend
    ports:
      - "3002:3002"
    volumes:
      - /root/pension/frontend_new_dist:/usr/share/nginx/html
    networks:
      - pension-net
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: pension-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Htht1234
      - MYSQL_DATABASE=pension_management_system
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pension-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

networks:
  pension-net:
    driver: bridge
