version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pension-backend
    network_mode: host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:13306/pension_management_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Htht1234
      - SERVER_PORT=8080
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pension-frontend
    network_mode: host
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: pension-mysql
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=Htht1234
      - MYSQL_DATABASE=pension_management_system
    volumes:
      - mysql_data:/var/lib/mysql
    command: --port=13306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "13306"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
