FROM openjdk:11-jre-slim

# 设置工作目录
WORKDIR /app

# 复制应用程序JAR文件
COPY target/onenet-push-demo-0.0.1-SNAPSHOT.jar app.jar

# 复制配置文件
COPY src/main/resources/application-demo.properties /app/application-demo.properties

# 暴露端口
EXPOSE 8081

# 设置启动命令
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=demo"]