-- 插入人脸识别一体机设备数据
-- 用于设备管理系统中的人脸识别设备监控

INSERT INTO smart_device (
    device_code,
    device_name,
    device_type,
    device_brand,
    device_model,
    device_status,
    purchase_date,
    installation_location,
    ip_address,
    mac_address,
    communication_protocol,
    alarm_threshold,
    battery_threshold,
    real_time_data,
    battery_level,
    signal_strength,
    last_communication_time,
    data_upload_status,
    warranty_expiry_date,
    maintenance_cycle,
    next_maintenance_date,
    failure_count,
    created_time,
    updated_time,
    created_by,
    updated_by,
    is_deleted
) VALUES (
    'FACE001',
    '门禁人脸识别一体机',
    '人脸识别设备',
    '海康威视',
    'DS-K1T671TM-3XF',
    '在线',
    '2024-01-15',
    '主入口门禁',
    '192.168.1.242',
    '00:11:22:33:44:55',
    'TCP/IP',
    '温度>60°C',
    20,
    '{"temperature":25.5,"humidity":45,"status":"normal"}',
    85,
    -45,
    NOW(),
    '正常',
    '2027-01-15',
    30,
    '2024-02-15',
    0,
    NOW(),
    NOW(),
    'system',
    'system',
    0
),
(
    'FACE002',
    '访客人脸识别终端',
    '人脸识别设备',
    '大华',
    'DHI-ASI7213Y-V3',
    '离线',
    '2024-01-20',
    '访客接待区',
    '192.168.1.243',
    '00:11:22:33:44:56',
    'TCP/IP',
    '温度>60°C',
    20,
    '{"temperature":26.2,"humidity":42,"status":"offline"}',
    0,
    0,
    DATE_SUB(NOW(), INTERVAL 2 MINUTE),
    '离线',
    '2027-01-20',
    30,
    '2024-02-20',
    1,
    NOW(),
    NOW(),
    'system',
    'system',
    0
);

-- 更新设备类型统计，确保包含人脸识别设备类型
-- 这个查询可以用来验证设备是否正确插入
SELECT 
    device_type,
    COUNT(*) as device_count,
    SUM(CASE WHEN device_status = '在线' THEN 1 ELSE 0 END) as online_count,
    SUM(CASE WHEN device_status = '离线' THEN 1 ELSE 0 END) as offline_count
FROM smart_device 
WHERE is_deleted = 0 
GROUP BY device_type;