server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pension_management_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Htht1234
    initialization-mode: never
  sql:
    init:
      mode: never

jwt:
  secret: pensionManagementSystemSecretKeyForHS512Algorithm2025SafeAndLongEnough
  expiration-ms: 86400000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.pension: DEBUG 